@startuml

!include https://raw.githubusercontent.com/mrorro/glue/main/mainEntities/puml/entity.puml
!include https://raw.githubusercontent.com/mrorro/glue/main/mainEntities/puml/resource.puml
!include https://raw.githubusercontent.com/mrorro/glue/main/mainEntities/puml/extension.puml
!include https://raw.githubusercontent.com/mrorro/glue/main/computingService/puml/executionEnvironment.puml
!include https://raw.githubusercontent.com/mrorro/glue/main/computingService/puml/acceleratorEnvironment.puml

Entity <|-- Resource
Entity *-- "+has" Extension
Resource <|--  ExecutionEnvironment

ExecutionEnvironment "1" -- "*" AcceleratorEnvironment
Entity <|-- AcceleratorEnvironment
@enduml


